# Generated by Django 4.2.27 on 2026-01-21 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("language", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Max number of enrollments (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "Facilitator"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enrolled", "Enrolled"), ("canceled", "Canceled")],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="events.event",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "Seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["starts_at"], name="events_starts__f39f74_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["language"], name="events_languag_767141_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["location"], name="events_locatio_2a4a74_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_by"], name="events_created_2c88fa_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["-created_at"], name="events_created_fc135f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["seeker", "status"], name="enrollments_seeker__d698c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["event", "status"], name="enrollments_event_i_cd4a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["-created_at"], name="enrollments_created_ee2bde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("event", "seeker")},
        ),
    ]
